require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Run pry"

task :start do
    #logging of SQL generated byb A-Record
    
    ActiveRecord::Base.logger = Logger.new(STDOUT)
    # Start pry sesh
    Pry.start
end